### ISSUE TITLE
 Failed to fetch the directory for api.letsencrypt.org.edgekey-staging.net

### ISSUE THREAD

**Issue by Prajithp** [sludin/Protocol-ACME#12]
Any idea why I'm getting this error?

```
root@sip [~/acme]# perl test.pl account_key.pem domain.csr test.crt
1453181509.684684 Private key loaded
Use of uninitialized value in numeric ne (!=) at /usr/local/share/perl5/Protocol/ACME.pm line 463.
Error occured: Status: 0, Detail: Failed to fetch the directory for api.letsencrypt.org.edgekey-staging.net, Type: unknown
```

**Comment by Prajithp** [comment]
Finally fixed this issue by updating the module. Now I'm getting different error, Could you please let me know what could be the reason for this error?

1453182790.327362 Polling for challenge fulfillment
1453182790.327381 Status: pending
1453182792.529419 Status: valid
1453182792.529459 Sending authz message for 
Error occured: Status: 400, Detail: Error creating new authz :: DNS name was empty, Type: urn:acme:error:malformed

**Comment by sludin** [comment]
It looks like you are not calling $acme->authz with a domain parameter.  You want to say:

$acme->authz( "www.example.com" );

or something similar.  If you post your source code I am happy to take a look at it.

**Comment by Prajithp** [comment]
Hi Sludin,

 Thanks for the comment. Managed to fix this issue by adding proper SAN entries :+1: 

Everything is good so far, so removing python dependencies from my project :) 

https://github.com/Prajithp/letsencrypt-cpanel

**Comment by Prajithp** [comment]
One more thing, how do I disable debug log? I tried to set log_level to ERROR but that doesn't help.

**Comment by sludin** [comment]
That is next on my list to take care of after I get some tests complete.  Give me a couple of days.

-stephen

**Comment by Prajithp** [comment]
Thanks. Please let us know once it is ready to use, so that I can update my code with this cool module.

**Comment by sludin** [comment]
Give it a try with the latest version ( 0.09 )
