### ISSUE TITLE
Crypt::RSA?

### ISSUE THREAD

**Issue by FGasper** [sludin/Protocol-ACME#2]
Hi Stephen,

Would Crypt::RSA work as a substitute for Crypt::OpenSSL::RSA and Bignum?

**Comment by sludin** [comment]
I'll check it out.  Thanks.

**Comment by sludin** [comment]
Thank you for pointing me to Crypt::RSA.  I looked at it and the first thing I noticed was that it uses Math::Pari which is also XS based.  If there is a reason that the XS for that is 'avoidable' I can look deeper.  I like the idea of a pure perl implementation so I am happy to entertain these types of side quests.

**Comment by FGasper** [comment]
Hmm … odd, as the POD starts off saying:

“Crypt::RSA is a pure-perl, cleanroom implementation of the RSA public-key cryptosystem.”

**Comment by FGasper** [comment]
Well, if all else fails, most systems have the OpenSSL binary … could fall back to that if Crypt::OpenSSL::RSA isn’t there?

**Comment by sludin** [comment]
Yes, that sounds like a solid idea.  The 'pure perl' part is that all of the RSA math is done in perl with assist from Math::Pari for some heavy lifting.

**Comment by sludin** [comment]
I just checked in a version that will allow you to indicate an openssl binary that you would like to use for crypto operations rather than Crypt::OpenSSL::RSA.  It will 'do the right thing' in the case you use openssl and not require the additional libraries.  Let me know how it works for you.
