### ISSUE TITLE
return the chain file

### ISSUE THREAD

**Issue by oetiker** [sludin/Protocol-ACME#23]
to deploy successfully we also need the chain file .. its location is indicated in the answer to the sign request:

```
$VAR1 = {
      'protocol' => 'HTTP/1.1',
      'headers' => {
                     'replay-nonce' => 'NJ6UUfvmmWkrs1gKZw0r8n5k-eNGiDUMVqGPGBQULns',
                     'date' => 'Tue, 26 Jan 2016 16:52:47 GMT',
                     'server' => 'nginx',
                     'connection' => 'keep-alive',
                     'content-type' => 'application/pkix-cert',
                     'strict-transport-security' => 'max-age=604800',
                     'content-length' => '1256',
                     'location' => 'https://acme-staging.api.letsencrypt.org/acme/cert/fa155815a55af231c0e0049b92a58068c154',
                     'link' => '<https://acme-staging.api.letsencrypt.org/acme/issuer-cert>;rel="up"',
                     'x-frame-options' => 'DENY'
                   },
      'status' => '201',
```

under headers->link

**Comment by sludin** [comment]
Do you have a preferred interface?  If called in arraycontext I can return the chain URI as a second parameter.

**Comment by oetiker** [comment]
from an api design point of view, I rather like to have non context sensitive return values ... 
maybe there could be a return object which I can ask for stuff if I want to and only if I use it in a string context it would stringify itself to the certificate.

**Comment by sludin** [comment]
Added a 'chain' call that can be used after you call sign.  Let me know what you think.

**Comment by oetiker** [comment]
great. just what I needed!
