### ISSUE TITLE
Accept keys/csrs as buffers?

### ISSUE THREAD

**Issue by FGasper** [sludin/Protocol-ACME#3]
Hello,

In our application we tend to work with keys, CSRs, and certificates as buffers rather than as files on disk. Could this module somehow support buffers rather than filesystem paths for things like sign()?

I’m happy to make this change myself if you’d rather; just want to run the idea by you first.

Thank you!

**Comment by sludin** [comment]
This is very doable.  I can do this in the next few days - that said I always welcome pull requests.

**Comment by FGasper** [comment]
On 5 Jan 2016 6:49 PM, Stephen Ludin wrote:

> This is very doable. I can do this in the next few days - that said I
> always welcome pull requests.

I’ll try to shoot a pull request your way on this.

Do you prefer a separate function, or passing a buffer as a SCALAR 
reference?

-FG

**Comment by sludin** [comment]
I think I’d prefer a scalar reference.  The rules would be:

scalar: assumed to be a filename
Scalar ref: assumed to be a ref to the buffer with the key

Is the overloading confusing?  I have seen similar interfaces in the past.  Another option is to use a different names parameter:

account_key – contains the buffer
account_key_file – contains a filename

Obviously this is redefining account_key but as this is under the ‘alpha’ shield I feel comfortable doing so.

-stephen

**Comment by FGasper** [comment]
On 5 Jan 2016 10:12 PM, Stephen Ludin wrote:

> I think I’d prefer a scalar reference. The rules would be:
> 
> scalar: assumed to be a filename
> Scalar ref: assumed to be a ref to the buffer with the key
> 
> Is the overloading confusing? I have seen similar interfaces in the
> past.

As have I, particularly in languages that make it as simple as Perl does.

I’ve tended lately to favor interfaces that are as simple to document as 
possible. This is partly because we’ve been burned when we wanted to 
make external APIs self-documenting, only to find that some of the 
interfaces had too much overloading and/or optional parameters (which, 
in turn, determined which other parameters were appropriate!) to work in 
that context.

Having multiple functions seems to make it a bit clearer what’s going 
on: a maintainer sees by the function name what the args are supposed to 
look like rather than wondering whether this/that argument can be 
written which way. Admittedly, it’s kind of a splitting-hairs in this 
instance.

> Another option is to use a different names parameter:
> 
> account_key – contains the buffer
> account_key_file – contains a filename

^^ This would be my preference.

> Obviously this is redefining account_key but as this is under the
> ‘alpha’ shield I feel comfortable doing so.

Agreed. :) Were P::A at production I’d say do the overloading, but as 
this is alpha it’s legit to change it.

-FG

**Comment by sludin** [comment]
Fixed in 0.06
