### ISSUE TITLE
Prerequisites too high?

### ISSUE THREAD

**Issue by melmothx** [sludin/Protocol-ACME#30]
Hello there!

On a debian jessie box, with some packages which are missing in stable backported, I have this outcome from the makefile:

Warning: prerequisite Crypt::OpenSSL::Bignum 0.06 not found. We have 0.04.
Warning: prerequisite Digest::SHA 5.95 not found. We have 5.88.
Warning: prerequisite HTTP::Tiny 0.054 not found. We have 0.050.
Warning: prerequisite JSON 2.90 not found. We have 2.61.
Warning: prerequisite Log::Any 1.032 not found. We have 0.15.
Warning: prerequisite Log::Any::Adapter 1.032 not found. We have 0.11.
Warning: prerequisite Log::Any::Adapter::Base 1.032 not found. We have 0.11.
Warning: prerequisite Log::Any::Adapter::Util 1.032 not found. We have 0.11.
Warning: prerequisite Test::Exception 0.43 not found. We have 0.35.

I'm wondering if these prerequisites are really needed, and if you are willing to accept patches to at least make possible a (totally unofficial) packaging for stable without upgrading/repackaging too much stuff.

Best wishes

**Comment by sludin** [comment]
You are likely correct. I took the latest as trying to sleuth how far back per modules it can safely go was a testing challenge that I did not take on. If you can confirm that it works with your setup I gladly update the dependencies. 

-stephen

**Comment by melmothx** [comment]
Stephen Ludin notifications@github.com writes:

> You are likely correct. I took the latest as trying to sleuth how far
> back per modules it can safely go was a testing challenge that I did
> not take on. If you can confirm that it works with your setup I gladly
> update the dependencies. 

I haven't (yet) started with the testing to put the deps back, because I
wanted to hear from you before taking any action.

Thanks for the reply. I'll come back to you when I'll have something in
my hands.

## 

Marco

**Comment by melmothx** [comment]
Debian has been notified: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813556#19
