### ISSUE TITLE
Support for account key rollover

### ISSUE THREAD

**Issue by twouters** [sludin/Protocol-ACME#36]
Would be nice to be able to perform a key rollover.

https://ietf-wg-acme.github.io/acme/#rfc.section.6.3.1

**Comment by twouters** [comment]
Looks like it hasn't been implemented in boulder yet.

**Comment by sludin** [comment]
Boulder has some gaps between the spec and implementation.  On the list for LE is to maintain a gap document, but it has not been created yet.

**Comment by sludin** [comment]
If you do notice things that boulder supports that P::A does not, please let me know.  Who knows, maybe another CA will support ACME in the meantime...

**Comment by twouters** [comment]
FYI - https://github.com/letsencrypt/boulder/pull/2231
Key rollover has been implemented in boulder. (the divergences document exists too)

**Comment by sludin** [comment]
Thanks.  It is on my to do list.  Knowing that there is interest will speed me up.

 

-stephen
