### ISSUE TITLE
Won't install without IO::Socket::Net

### ISSUE THREAD

**Issue by maettu** [sludin/Protocol-ACME#37]
`cpanm Protocol::ACME`fails during the tests if `IO::Socket::Net` is not installed. The errror messages, however, are not very explanatory. You see fails with `malformed JSON string, neither array, object, number, string or atom, at character offset 0`.

Looking into the code shows that the content field of a request is not a JSON, but a simple string, which in turn makes the json_decode fail.

Inserting something along a `die` produces more informative error messages in the TAP:

```
sub _request_get
{
  my $self = shift;
  my $url  = shift;
  my $nodecode = shift || 0;

  die $resp->{content} unless $resp->{success};
  ...
```

another approach would be to make IO::Socket::Net a dependency.

Would you like me to produce a pull request, and if yes, into which direction should it go? (This is not a promise that I will supply whatever you ask for, though :-) )

**Comment by sludin** [comment]
Maettu,

Do you mean IO::Socket::INet?  If so then that is a dependency of HTTP::Tiny, or at least it should be.  Can you send me any information you have on the failed install?  Adding the appropriate dependencies it the ‘right’ way to fix this, but I am very happy to improve the error messaging as well.

-stephen

**Comment by maettu** [comment]
Stephen,

Sorry.. IO::Socket::SSL.

Here are my reproduction steps.

```
$ perlbrew lib create 5.16.3@test
lib 'perl-5.16.3@test' is created.
$ cpanm Protocol::ACME
--> Working on Protocol::ACME
$ tail .cpanm/work/1470683772.31433/build.log
t/04-load_key_crypt.t  (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  3-5
  Non-zero exit status: 3
Files=5, Tests=66,  4 wallclock secs ( 0.02 usr  0.06 sys +  2.27 cusr  1.44 csys =  3.79 CPU)
Result: FAIL
Failed 2/5 test programs. 6/66 subtests failed.
Makefile:864: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 3
-> FAIL Installing Protocol::ACME failed. See .cpanm/work/1470683772.31433/build.log for details. Retry with --force to force install it.
Expiring 34 work directories.
```

and the relevant part of the build log:

```
perl5/perlbrew/perls/perl-5.16.3/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t .............. ok
t/01-dependency_check.t .. ok
Use of uninitialized value in sprintf at /home/bloch/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Crypt/RSA/Parse/Parser.pm line 46.
t/02-load_key.t .......... ok

#   Failed test 'Get the ACME directory'
```

This is not very informative, therefore I ran test 03 manually: (with `use lib ("lib")`)

```
$ perl t/03-load_key_openssl.t
1..5
ok 1 - Create ACME Object
ok 2
not ok 3 - Get the ACME directory
#   Failed test 'Get the ACME directory'
#   at t/03-load_key_openssl.t line 51.
# died: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "IO::Socket::SSL 1.42...") at lib/Protocol/ACME.pm line 1044.
Use of uninitialized value $nonce in concatenation (.) or string at lib/Protocol/ACME.pm line 1026.
...
```

Also, this is not very to the point, however tells me what to do.

```
$ cpanm IO::Socket::SSL
```

Now, test runs:

```
$ perl t/03-load_key_openssl.t
1..5
ok 1 - Create ACME Object
ok 2
ok 3 - Get the ACME directory
ok 4 - Register
ok 5 - Accept TOS
```

..and Protocol::ACME installs:

```
$ cpanm Protocol::ACME
--> Working on Protocol::ACME
Fetching http://www.cpan.org/authors/id/S/SL/SLUDIN/Protocol-ACME-0.15.tar.gz ... OK
Configuring Protocol-ACME-0.15 ... OK
Building and testing Protocol-ACME-0.15 ... OK
Successfully installed Protocol-ACME-0.15
1 distribution installed
```

Cheers
:m)

**Comment by sludin** [comment]
Thanks, that is helpful.  This is the result of a desire by user to be able to NOT have to install IO::Socket::SSL and use an installed openssl binary instead.  I admit it is awkward for dependencies to be conditional.  Any suggestion to shore that up is welcome.

Now, the 03-load_key_openssl.t tests should NOT be using IO::Socket::SSL at all.  It should be run if the openssl binary is found and not leverage the perl lib.  I’ll look into this.

-stephen

**Comment by sludin** [comment]
Figured it out.  HTTP::Tiny has an implicit dependency on IO::Socket::SSL and Net::SSLeay if you make TLS requests (which we do).  I added the dependencies and caught the lower level errors to make future debugging of API calls easier.

**Comment by sludin** [comment]
BTW - changes are in 0.16.

**Comment by maettu** [comment]
thank you. Works for me now.
