### ISSUE TITLE
autoconf/automake

### ISSUE THREAD

**Issue by oetiker** [sludin/Protocol-ACME#9]
I can provide a set of automake files to make Protocol-ACME into a simple no-dependency installable tool. full configure && make install glory ... 

interested ?

**Comment by sludin** [comment]
Very interested.  I want to make sure though that people can still just install the library via CPAN.  Perhaps though the right thing to do is to have a separate ‘project’ that leverages the library.  When you install your tool you get a fully functional client which by definition installs the library, or you could just install the binary.  Or some other variant?  

-stephen

**Comment by oetiker** [comment]
OK, a separate project, something based on your client.pl ... my idea is to have a tool where I can specify in a JSON config file all the info required, and then have the tool go off and do it's thing by just running it ... as the certificates are only valid for a few months.

**Comment by sludin** [comment]
Tobias,

I think the idea is great and I’d love to help.  I am not really trying to create a client but rather a library a client could be built from what you describe is a perfect compliment.  My client.pl is more of a ‘this is one way to do it’ rather than something intended to be installed and run.

Let me know how I can help.  Tweaks and extensions to the library to make your client more robust and easier to code are very welcome.

-stephen

**Comment by oetiker** [comment]
will let you know if I need changes, or send you pull requests ..  ACMEfetch is as yet unknown to the intertubes .. so this might be a good name. what do you think?

**Comment by sludin** [comment]
That is a good name. At our last ISRG/LE board meeting we discussed client and library naming and it is very important that we not use Let's Encrypt in it. Who knows - perhaps another CA will implement the ACME protocol. 

Send me a pointer to the project when you have it set up. 

-stephen

**Comment by oetiker** [comment]
some initial code ... https://github.com/oetiker/AcmeFetch pull and ./bootstrap

it does not do anything besides loading the config file ... but the rest will basically come from your sample client.pl

to build a distro including all the dependencies:

```
git clone ...
cd AcmeFetch
./bootstrap
rm -rf thirdparty/CPAN
PERL=/opt/myold/perl-5.10.2/bin/perl ./configure
make dist
```

the resulting tar file contains now a classic configure make install thing including all the non core perl modules required to build on a perl >= 5.10.2

**Comment by oetiker** [comment]
First working release is published: https://github.com/oetiker/AcmeFetch/releases

**Comment by sludin** [comment]
This is great stuff.  I built and installed it from the 0.1.0 tarball.  You saw the resulting issues and pull request.  Nice work.  I am going to plan on using this.

The last thing the newbie would need is a crontab spit that they can use to run once a month or so.  I think mucking with web server config files is out of the scope of a tool like this (unlike the python client).  It would be great, however, to point folks to instructions for the most common platforms out there.

-stephen
